#!/usr/bin/env python3
"""Generate a combinatorial TC-AC-01 profile sweep.

Varies three axes that are genuinely read by the harness's simulators (verified against
simulator/tc_ac_01_transceiver.go and drivers/jmrtd/.../TcAc01CardService.java before this
generator was written — see docs/PROVENANCE.md "sweep axes" note):

  - MRZ triple (document_number, date_of_birth, date_of_expiry) — feeds the BAC key
    derivation (password.NewPasswordMrzi), producing genuinely different K_ENC/K_MAC per
    profile, not just different labels.
  - PACE failure status word (pace_sw) — returned verbatim by the simulator on the failing
    APDU; this was already wired before this generator was written.
  - PACE injection point (pace_fail_on) — "mse_set_at" (fail before key agreement begins,
    the original/published behavior) vs "general_authenticate" (MSE:Set AT succeeds, first
    General Authenticate call fails instead). This axis was NOT wired before this generator
    was written; see simulator/tc_ac_01_transceiver.go for the implementation added
    alongside this script. It is a deliberate two-point simplification of the real
    four-exchange PACE state machine, not a full per-substep sweep — stated explicitly here
    and must be stated explicitly in the paper's methodology section.

This does not touch profiles/pace-then-bac-downgrade.json (the tag blog-b10-2026-07 pinned
profile) — that profile is immutable and cited externally. All generated profiles are new
files under profiles/sweep/.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "profiles" / "sweep"
CARD_ACCESS_HEX = "31143012060A04007F0007020204020402010202010D"  # same PACEInfo as the pinned profile

# Five MRZ triples: the original pinned document plus four synthetic others. All are
# well-formed enough for password.NewPasswordMrzi / BACKey to derive a key from (this
# harness does not validate ICAO check digits — it only needs distinct byte strings that
# feed the KDF, since we are testing host-stack decision logic, not MRZ OCR/parsing).
MRZ_VARIANTS = [
    {"id": "orig", "document_number": "L898902C", "date_of_birth": "690806", "date_of_expiry": "940623"},
    {"id": "alt1", "document_number": "P4159874A", "date_of_birth": "850214", "date_of_expiry": "300214"},
    {"id": "alt2", "document_number": "X0000001B", "date_of_birth": "010101", "date_of_expiry": "350101"},
    {"id": "alt3", "document_number": "D7742093C", "date_of_birth": "991231", "date_of_expiry": "290615"},
    {"id": "alt4", "document_number": "S1122334D", "date_of_birth": "751107", "date_of_expiry": "271107"},
]

# Five plausible ISO 7816 / PACE-rejection status words. 6FFF (the pinned profile's value)
# is a proprietary/vendor "card dead" convention retained for continuity; the other four are
# standard ISO 7816-4 codes a real chip could plausibly return during PACE key agreement.
STATUS_WORDS = [
    "6FFF",  # proprietary "card dead" (original pinned value)
    "6300",  # authentication failed
    "6982",  # security status not satisfied
    "6A88",  # referenced data not found
    "6A80",  # incorrect parameters in data field
]

INJECTION_POINTS = ["mse_set_at", "general_authenticate"]


def profile_id(mrz_id: str, sw: str, fail_on: str) -> str:
    return f"TC-AC-01-sweep-{mrz_id}-{sw.lower()}-{fail_on}"


def build_profile(mrz: dict, sw: str, fail_on: str) -> dict:
    pid = profile_id(mrz["id"], sw, fail_on)
    return {
        "id": pid,
        "name": f"Sweep profile: mrz={mrz['id']} sw={sw} fail_on={fail_on}",
        "mechanism": "PACE",
        "condition": "pace_fail_then_bac",
        "tier": "wire",
        "seed": 1,
        "mrz": {
            "document_number": mrz["document_number"],
            "date_of_birth": mrz["date_of_birth"],
            "date_of_expiry": mrz["date_of_expiry"],
        },
        "card_access_hex": CARD_ACCESS_HEX,
        "injection": {
            "pace_fail_on": fail_on,
            "pace_sw": sw,
            "notes": "Generated by profiles/generate_sweep.py — synthetic, no physical passport.",
        },
        "sweep_axes": {"mrz_id": mrz["id"], "pace_sw": sw, "pace_fail_on": fail_on},
    }


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    entries = []
    for mrz in MRZ_VARIANTS:
        for sw in STATUS_WORDS:
            for fail_on in INJECTION_POINTS:
                profile = build_profile(mrz, sw, fail_on)
                path = OUT_DIR / f"{profile['id']}.json"
                text = json.dumps(profile, indent=2) + "\n"
                path.write_text(text, encoding="utf-8")
                entries.append(
                    {
                        "id": profile["id"],
                        "path": str(path.relative_to(ROOT)),
                        "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
                        "sweep_axes": profile["sweep_axes"],
                    }
                )

    manifest = {
        "generator": "profiles/generate_sweep.py",
        "generated_profile_count": len(entries),
        "axes": {
            "mrz_variants": [m["id"] for m in MRZ_VARIANTS],
            "status_words": STATUS_WORDS,
            "injection_points": INJECTION_POINTS,
        },
        "profiles": entries,
    }
    (ROOT / "profiles" / "sweep_index.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Generated {len(entries)} profiles under {OUT_DIR}")
    print(f"Index written to profiles/sweep_index.json")


if __name__ == "__main__":
    main()
